### ISSUE TITLE
[QUESTION]: What does lock do?

### ISSUE THREAD

**Issue by supercrafter333** [CzechPMDevs/ImageOnMap#1]
What is the variable `lock` doing?

**Comment by VixikHD** [comment]
I cannot find any `lock` variable inside the source.. Could you please be more specific?

**Comment by supercrafter333** [comment]
I mean https://github.com/CzechPMDevs/ImageOnMap/blob/main/src/czechpmdevs/imageonmap/utils/ImageLoader.php#L57

**Comment by supercrafter333** [comment]
What does locked mean?

**Comment by VixikHD** [comment]
It should have been forwarded to ClientboundMapItemDataPacket, but since it's not, it does nothing.
