### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GamerMJay** [CzechPMDevs/ImageOnMap#13]
Hey, I created a map but after every restart it is invisibl
![Screenshot 2022-06-09 164652](https://user-images.githubusercontent.com/66413999/172876157-50d74455-cff2-4cac-bfaf-5020a5ecab7d.png)
![Screenshot 2022-06-09 164811](https://user-images.githubusercontent.com/66413999/172876161-d0f8ca83-3ddc-428a-9747-6386eec010a9.png)
e

**Comment by VixikHD** [comment]
Are you using stop command to restart the server?

**Comment by ZippingBoat9588** [comment]
@VixikHD Same By me after restart map and Item frame clear

**Comment by VixikHD** [comment]
Server must be stopped down properly using 'stop' command to store available maps in order to load maps properly after start.

**Comment by ZippingBoat9588** [comment]
@VixikHD nah i restart my Server and then the Map is clear

**Comment by VixikHD** [comment]
put it on to item frame

**Comment by VixikHD** [comment]
this is client sided bug, I need more time to fix that

**Comment by ZippingBoat9588** [comment]
I Put it all time in frame but after restart its clear

**Comment by VixikHD** [comment]
https://github.com/CzechPMDevs/ImageOnMap/issues/13#issuecomment-1215978731

**Comment by ZippingBoat9588** [comment]
Nah i dont use /stop

**Comment by VixikHD** [comment]
that's the problem, you have to use it
