### ISSUE TITLE
PM 4.6.0 Bug....

### ISSUE THREAD

**Issue by DaDevGuy** [CzechPMDevs/ImageOnMap#15]
* I Updated Server To Pocketmine 4.6.0 But After Updating When i teleport between 2 worlds the image become this
![image](https://user-images.githubusercontent.com/95925949/179340275-3a84d576-7d20-41d4-abfe-30874581d1bd.png)

* Please Fix It

**Comment by VixikHD** [comment]
This is client sidded bug. It is going to be debugged in next PocketMine version (4.6.1). You can use dev build with [this commit](https://github.com/pmmp/PocketMine-MP/commit/2b61c025c26394c3293bcc12a2d0b2301cb4c7ee) in order to fix that.
