### ISSUE TITLE
Image Disappears 

### ISSUE THREAD

**Issue by sulimanzeen** [CzechPMDevs/ImageOnMap#20]
Hello

I noticed images do keep disappearing when the server restarts. There is no error in the console when this happens. 

The image will appear when players click on it. but what only appears a part of the image, not the full image. Although, The only way to get the full image to appear is by clicking all the item frames.

**Comment by VixikHD** [comment]
What minecraft version are you running the server on?

**Comment by sulimanzeen** [comment]
Minecraft version 1.19.20 

And Pocketmine version is currently in 4.7.1

**Comment by VixikHD** [comment]
Was the problem occuring back in 1.19.10?

**Comment by sulimanzeen** [comment]
I really have no idea about that. Because I started using your plugin 1 week ago. But I have tested this plugin in a different providers and it didn't work out.

**Comment by sulimanzeen** [comment]
I do think if you add a function that reloads a chunk when players spawn & join would fix the issue.

**Comment by VixikHD** [comment]
Fixed in #26
