### ISSUE TITLE
Image is Blank

### ISSUE THREAD

**Issue by MulqiGaming64** [CzechPMDevs/ImageOnMap#22]
When /image obtain or get image from Api Code, the image on the map doesn't exist, unless you first place it into an ItemFrame and then destroy it again and then the image is on the map.

Image: 
![Screenshot_20221017-053330](https://user-images.githubusercontent.com/55838823/196061935-c2f908db-265c-4ce7-85d2-f46339173ffa.jpg)

**System information (please complete the following information):**
- OS: Ubuntu 20.04
- php version 8.0.24

**Comment by VixikHD** [comment]
Fixed in #26
