### ISSUE TITLE
Blank/invis maps

### ISSUE THREAD

**Issue by KingOfTurkey38** [CzechPMDevs/ImageOnMap#25]
**Describe the bug**
Maps are blank/invisible Tested with many images with any size.

**To Reproduce**
1: put an image in plugin data folder
2: obtain the map with: /img o <image name>

**Expected behavior**
It's supposed to display the image

**Screenshots**
https://prnt.sc/90Lpm0dGiwdf
https://prnt.sc/q3kIuNXUJaPX

**System information (please complete the following information):**
- OS: Windows 10 and ubuntu 20.04
- php version 8.0.22
- ImageOnMap v1.0.3 (dev build 17)

**Additional context**

**Comment by Anton22q** [comment]
++

**Comment by frizib** [comment]
A similar situation on a similar system
