### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by xFungal** [CzechPMDevs/ImageOnMap#29]
It says to break both ItemFrames once I run the place command.  I broke the first item frame and it worked fine, and then I broke the second frame and the server keeps crashing each time I break the second one.  Here is the error I am getting:

[Server thread/CRITICAL]: ErrorException: "imagecreatefrompng(): "/server/server-data/plugin_data/ImageOnMap/images/sunset.png" is not a valid PNG file" (EXCEPTION) in "plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/utils/ImageLoader" at line 63
--- Stack trace ---
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[108] imagecreatefrompng(): "/server/server-data/plugin_data/ImageOnMap/images/sunset., string[99] phar:///server/server-data/plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/ut, int 63)
#1 plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/utils/ImageLoader(63): imagecreatefrompng(string[60] /server/server-data/plugin_data/ImageOnMap/images/sunset.png)
#2 plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/DataProviderTrait(88): czechpmdevs\imageonmap\utils\ImageLoader::loadImage(string[60] /server/server-data/plugin_data/ImageOnMap/images/sunset.png, int 5, int 3, int 0, int 2)
#3 plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/ImagePlaceSession(211): czechpmdevs\imageonmap\ImageOnMap->getImageFromFile(string[60] /server/server-data/plugin_data/ImageOnMap/images/sunset.png, int 5, int 3, int 0, int 2)
#4 plugins/ImageOnMap.phar/src/czechpmdevs/imageonmap/ImagePlaceSession(94): czechpmdevs\imageonmap\ImagePlaceSession->finish()
#5 pmsrc/src/event/RegisteredListener(60): czechpmdevs\imageonmap\ImagePlaceSession->onBreak(object pocketmine\event\block\BlockBreakEvent#159516)
#6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\block\BlockBreakEvent#159516)
#7 pmsrc/src/world/World(1852): pocketmine\event\Event->call()
#8 pmsrc/src/player/Player(1685): pocketmine\world\World->useBreakOn(object pocketmine\math\Vector3#159969, object pocketmine\item\ItemBlock#161833, object pocketmine\player\Player#127406, true)
#9 pmsrc/src/network/mcpe/handler/InGamePacketHandler(458): pocketmine\player\Player->breakBlock(object pocketmine\math\Vector3#159886)
#10 pmsrc/src/network/mcpe/handler/InGamePacketHandler(257): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#128348)
#11 pmsrc/vendor/pocketmine/bedrock-protocol/src/PlayerAuthInputPacket(251): pocketmine\network\mcpe\handler\InGamePacketHandler->handlePlayerAuthInput(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#160589)
#12 pmsrc/src/network/mcpe/NetworkSession(450): pocketmine\network\mcpe\protocol\PlayerAuthInputPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#157020)
#13 pmsrc/src/network/mcpe/NetworkSession(406): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#160589, string[112] .........A...C..hC!.!C...........A.............24......C5...............C..hC!.!)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(183): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[88] c.abbF....9>I.bx).x......2..%...`.(....q....a!.]n#.......r6e``:.........V. ..p..)
#15 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[97] .7.....x0...W.......7=..fa....e$.:O.f...........<.PoCD.....+rU..Ux...V.P...=.5fo)
#16 pmsrc/src/network/mcpe/raklib/RakLibInterface(113): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#30663)
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#19 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1674922566.8398)
#20 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[20] /server/server-data/, string[28] /server/server-data/plugins/)
#22 pmsrc/src/PocketMine(362): pocketmine\server()
#23 pmsrc(11): require(string[55] phar:///server/jars/pmmp-4.12.8.phar/src/PocketMine.php)
--- End of exception information ---
[16:16:06.833] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:16:06.851] [Server thread/EMERGENCY]: Please upload the "/server/server-data/crashdumps/Sat_Jan_28-16.16.06-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[16:16:07.308] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/8225605 or use the ID #8225605.
[16:16:07.308] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by VixikHD** [comment]
Read the errror: /server/server-data/plugin_data/ImageOnMap/images/sunset.png" is not a valid PNG file

Your picture is not valid PNG file.
