### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by MulqiGaming64** [CzechPMDevs/ImageOnMap#3]
Code:

```php
$file = $this->getDataFolder() . "test.png";
$mapid = ImageOnMap::getInstance()->getImageFromFile($file, 1, 1, 0, 0);
/** @var FilledMap $map */
$map = (FilledMap::get())->setMapId($mapid);

$player->getInventory()->setItemInHand($map);
```

Why my Minecraft force close? the code is correct right?

**Comment by VixikHD** [comment]
Yep, you used the api right way. Seems like the problem is on Mojang's side. However, could you please send me "test.png" file?

**Comment by MulqiGaming64** [comment]
![test](https://user-images.githubusercontent.com/55838823/148625580-31f90455-1fe3-471f-9105-129daa8bc0d8.png)

**Comment by MulqiGaming64** [comment]
Is it because of the size of the image? Image size is 60x60, and when I try not to use api, but use /image obtain

the map is empty, there are no pictures:

![Screenshot_20220108-083415](https://user-images.githubusercontent.com/55838823/148626435-39dce6de-e893-4a00-94cd-7d68ce079e7c.jpg)

**Comment by MulqiGaming64** [comment]
I have found the problem from the bug, You cannot set FilledMap items in hand or slot held items, because the Map must be loaded first

Thx for making this plugins

**Comment by MulqiGaming64** [comment]
the problem is finished
